version = 1

[envs.black]
channels = ["conda-forge"]
dependencies = { black = "*" }
exposed = { black = "black", blackd = "blackd" }

[envs.pre-commit]
channels = ["conda-forge"]
dependencies = { pre-commit = "*" }
exposed = { pre-commit = "pre-commit" }

[envs.yamllint]
channels = ["conda-forge"]
dependencies = { yamllint = "*" }
exposed = { yamllint = "yamllint" }

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

[envs.snakeviz]
channels = ["conda-forge"]
dependencies = { snakeviz = "*" }
exposed = { snakeviz = "snakeviz" }

[envs.jupyter]
channels = ["conda-forge"]
dependencies = { jupyter = "*", jupyter-lsp = "*", jupyterlab-lsp = "*", python-lsp-server = "*", python-lsp-black = "*", python-lsp-ruff = "*" }
exposed = { jupyter = "jupyter" }

[envs.direnv]
channels = ["conda-forge"]
dependencies = { direnv = "*" }
exposed = { direnv = "direnv" }

[envs.jq]
channels = ["conda-forge"]
dependencies = { jq = "*" }
exposed = { jq = "jq" }

[envs.grayskull]
channels = ["conda-forge"]
dependencies = { grayskull = "*" }
exposed = { grayskull = "grayskull" }

[envs.conda-smithy]
channels = ["conda-forge"]
dependencies = { conda-smithy = "*" }
exposed = { feedstocks = "feedstocks", conda-smithy = "conda-smithy" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.conda-build]
channels = ["conda-forge"]
dependencies = { conda-build = "*" }
exposed = { conda-build = "conda-build", conda-convert = "conda-convert", conda-debug = "conda-debug", conda-develop = "conda-develop", conda-inspect = "conda-inspect", conda-metapackage = "conda-metapackage", conda-render = "conda-render", conda-skeleton = "conda-skeleton" }

[envs.tox]
channels = ["conda-forge"]
dependencies = { tox = "*" }
exposed = { tox = "tox" }
