version = 1

[envs.black]
channels = ["conda-forge"]
dependencies = { black = "*", jupyter = "*" , ipython = "*", tokenize-rt = "*" }
exposed = { black = "black", blackd = "blackd" }

[envs.pre-commit]
channels = ["conda-forge"]
dependencies = { pre-commit = "*" }
exposed = { pre-commit = "pre-commit" }

[envs.yamllint]
channels = ["conda-forge"]
dependencies = { yamllint = "*" }
exposed = { yamllint = "yamllint" }

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

[envs.snakeviz]
channels = ["conda-forge"]
dependencies = { snakeviz = "*" }
exposed = { snakeviz = "snakeviz" }

[envs.jupyter]
channels = ["conda-forge"]
dependencies = { jupyter = "*", jupyterlab_execute_time = "*", jupyter-lsp = "*", jupyterlab-lsp = "*", python-lsp-server = "*", python-lsp-black = "*", python-lsp-ruff = "*", jupyterlab_vim = "*" }
exposed = { jupyter = "jupyter" }

[envs.direnv]
channels = ["conda-forge"]
dependencies = { direnv = "*" }
exposed = { direnv = "direnv" }

[envs.jq]
channels = ["conda-forge"]
dependencies = { jq = "*" }
exposed = { jq = "jq" }

[envs.grayskull]
channels = ["conda-forge"]
dependencies = { grayskull = "*" }
exposed = { grayskull = "grayskull" }

[envs.conda-smithy]
channels = ["conda-forge"]
dependencies = { conda-smithy = "*" }
exposed = { feedstocks = "feedstocks", conda-smithy = "conda-smithy" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.conda-build]
channels = ["conda-forge"]
dependencies = { conda-build = "*" }
exposed = { conda-build = "conda-build", conda-convert = "conda-convert", conda-debug = "conda-debug", conda-develop = "conda-develop", conda-inspect = "conda-inspect", conda-metapackage = "conda-metapackage", conda-render = "conda-render", conda-skeleton = "conda-skeleton" }

[envs.keyring]
channels = ["conda-forge"]
dependencies = { keyring = "*" }
exposed = { keyring = "keyring" }

[envs.uv]
channels = ["conda-forge"]
dependencies = { uv = "*" }
exposed = { uv = "uv", uvx = "uvx" }

[envs.pdm]
channels = ["conda-forge"]
dependencies = { pdm = "*", setuptools = "*" }
exposed = { pdm = "pdm" }

[envs.tox]
channels = ["conda-forge"]
dependencies = { tox = "*", tox-current-env = "*", tox-uv = "*", python-uv = "*" }
exposed = { tox = "tox" }

[envs.feedrattler]
channels = ["conda-forge"]
dependencies = { feedrattler = "*" }
exposed = { feedrattler = "feedrattler" }

[envs.ipython]
channels = ["conda-forge"]
dependencies = { ipython = "*" }
exposed = { ipython = "ipython", ipython3 = "ipython3" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "3.12.*" }
exposed = { "python3.12" = "python3.12" }

[envs.conda-recipe-manager]
channels = ["conda-forge"]
dependencies = { conda-recipe-manager = "*" }
exposed = { conda-recipe-manager = "conda-recipe-manager", crm = "crm" }

[envs.fish]
channels = ["conda-forge"]
dependencies = { fish = "*" }
exposed = { fish = "fish", fish_indent = "fish_indent", fish_key_reader = "fish_key_reader" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.python-lsp-server]
channels = ["conda-forge"]
dependencies = { python-lsp-server = "*", python-lsp-ruff = "*", pylsp-rope = "*" }
exposed = { pylsp = "pylsp" }

[envs.lua-language-server]
channels = ["conda-forge"]
dependencies = { lua-language-server = "*" }
exposed = { lua-language-server = "lua-language-server" }
