set nocompatible              " be iMproved, required
if empty(glob('$HOME/.vim/autoload/plug.vim'))
  silent !curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'lifepillar/vim-solarized8'
call plug#end()

filetype plugin indent on    " required

" General settings
syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set number
set colorcolumn=80
let mapleader=","
set backspace=indent,eol,start

" General mappings
imap kj <Esc>

" Solarized stuff
if exists('+termguicolors')
    " :h xterm-true-color
    set termguicolors
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
set background=dark
autocmd vimenter * ++nested colorscheme solarized8_flat
let g:solarized_statusline = "flat"

