set nocompatible              " be iMproved, required
if empty(glob('$HOME/.vim/autoload/plug.vim'))
  silent !curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'altercation/vim-colors-solarized'
call plug#end()

filetype plugin indent on    " required

" General settings
syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set number
set colorcolumn=80
let mapleader=","
set backspace=indent,eol,start

" General mappings
imap kj <Esc>

" Solarized stuff
set background=dark
colorscheme solarized
set t_Co=16
